---
title: "HW2Q2"
format: html
---

```{r}
library(tidyverse)
library(logistf)
library(readxl)
library(maditr)
library(sjPlot)
library(knitr)
library(kableExtra)
library(pROC)
```

```{r}
main <- read_csv("full_v5.csv")
cols <- tibble(Index = seq_along(names(main)), Name = names(main))
```

```{r}
#kable(cols, format = "latex", booktabs = TRUE)
cols

multiple_patients <- main %>%
  count(ip_patient_id) %>%
  arrange(desc(n)) %>%
  filter(n > 1) %>%
  pull(ip_patient_id)

# make multiple encounters var

main <- main %>%
  mutate(
    multiple_encounters = if_else(ip_patient_id %in% multiple_patients, 1, 0)
  )

main %>%
  count(multiple_encounters) %>%
  arrange(desc(n))

```



```{r}
# create logist model
fir <- logistf(antibiotics_after_procedure_less_thirty ~ 
                 category2 + Autoimmune + Diabetes + 
                 Immunocompromise + Tobacco + Vascular + 
                 multiple_encounters + mohs + elix_vw_score + preventive_antibiotics, 
               data = main, firth = T, pl = T)

```

```{r}
# view model results
summary(fir)

# view coefficients
exp(coef(fir))

# view 95% confidence intervals
round(exp(cbind(Estimate=coef(fir), confint(fir))), 4)
```

Get the coefs table, exponentiate coefs, and then output it nicely:

```{r}
coefs_table <- data.frame(round(exp(cbind(Estimate=coef(fir), confint(fir))), 4))
coefs_table <- coefs_table %>%
  mutate(Estimate = exp(Estimate), Lower.95. = exp(Lower.95.), Upper.95. = exp(Upper.95.)) %>%
  rename(`exp(Coef Estimate)` = Estimate, `exp(Lower 95%)` = Lower.95., `exp(Upper 95%)` = Upper.95.) %>%
  mutate(`exp(Coef Estimate)` = format(`exp(Coef Estimate)`, scientific = FALSE))
head(coefs_table, n=17)

kable(coefs_table, format = "latex", booktabs = TRUE)
```


```{r}
# apply exponentiation to all model coefficients and confidence intervals
exp_fir <- fir
exp_fir$coefficients <- exp(exp_fir$coefficients)
exp_fir$ci.upper <- exp(exp_fir$ci.upper)
exp_fir$ci.lower <- exp(exp_fir$ci.lower)

print(fir$coefficients)
cat("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "\n")
print(exp_fir$coefficients)
cat("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", "\n")
print(fir$ci.upper)
cat("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "\n")
print(exp_fir$ci.upper)
cat("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", "\n")
print(fir$ci.lower)
cat("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "\n")
print(exp_fir$ci.lower)
cat("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", "\n")
```


```{r}
# plot 
plot_model(fir)
plot_model(exp_fir) 
```

Create a contingency table for (antibiotics_after_procedure_less_thirty) and category2

```{r}
contigency <- table(Response = main$antibiotics_after_procedure_less_thirty, Body_Part = main$category2)
contigency_m <- as.data.frame.matrix(contigency)

kbl(contigency_m) %>%
  add_indent(c(1:2)) %>%
  add_header_above(c("Body Part" = 9)) %>%
  kable_paper("striped", full_width = F) %>%
  row_spec(0, angle = -30, font_size = 10) %>%
  column_spec(1, bold = T, border_right = T) %>%
  pack_rows("Response", 1, 2)
```

ROC Curve

```{r}
probs <- predict(fir, type = "response")
roc_m <- roc(main$antibiotics_after_procedure_less_thirty, probs)
plot(roc_m, col='blue', main = "ROC Curve", print.auc = TRUE)
```

